data <- read.csv("household_power_consumption.txt", header = T, sep = ';', na.strings = "?") 
data$Date <- as.Date(data$Date, format = "%d/%m/%Y")
subset_data <- data[data$Date == '2007-02-01' | data$Date == '2007-02-02',]
datetime <- paste(as.Date(subset_data$Date), subset_data$Time)
subset_data$Datetime <- as.POSIXct(datetime)
png(file="plot4.png", width = 480, height = 480, bg="white")
par(mfrow = c(2,2), mar = c(4,4,2,1), oma = c(0,0,2,0))
plot(subset_data$Global_active_power ~ subset_data$Datetime, type = "l", ylab = "Global Active Power")
plot(subset_data$Voltage ~ subset_data$Datetime, type = "l", ylab = "Voltage", xlab = "datetime")
plot(subset_data$Sub_metering_1 ~ subset_data$Datetime, type = "l", ylab = "Energy sub metering",xlab = "")
lines(subset_data$Sub_metering_2 ~ subset_data$Datetime, col = 'Red')
lines(subset_data$Sub_metering_3 ~ subset_data$Datetime, col = 'Blue')
legend("topright", col = c("black", "red", "blue"), lty = 1, lwd = 2, bty = "n", legend = c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"))
plot(subset_data$Global_reactive_power ~ subset_data$Datetime, type = "l", ylab = "Global_rective_power", xlab = "datetime")
dev.off()

